version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elkk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elkk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elkk
    depends_on:
      - elasticsearch

  zookeeper:
    build:
      context: zookeeper/
      args:
        ZK_VERSION: $ZK_VERSION
    volumes:
      - type: bind
        source: ./zookeeper/config/zookeeper.cfg
        target: /conf/zoo.cfg
        read_only: true
    ports:
      - "2181:2181"
    networks:
      - elkk

  kafka:
    build:
      context: kafka/
      args:
        SCALA_VERSION: $SCALA_VERSION
        KAFKA_VERSION: $KAFKA_VERSION
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.22.33
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - type: bind
        source: ./kafka/config/server.properties
        target: /opt/kafka/config/server.properties
        read_only: true
    networks:
      - elkk
    depends_on:
      - zookeeper

networks:
  elkk:
    driver: bridge

volumes:
  elasticsearch:
