version: '3.8'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /opt/elkk/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /opt/elkk/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elkk

  logstash:
    build:
      context: .
      dockerfile: ./logstash/Dockerfile
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /opt/elkk/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/logstash.conf
        target: /opt/elkk/logstash/pipeline/logstash.conf
        read_only: true
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elkk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: .
      dockerfile: ./kibana/Dockerfile
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /opt/elkk/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elkk
    depends_on:
      - elasticsearch

  zookeeper:
    build:
      context: .
      dockerfile: ./zookeeper/Dockerfile
    volumes:
      - type: bind
        source: ./zookeeper/config/zookeeper.cfg
        target: /opt/elkk/zookeeper/conf/zoo.cfg
    ports:
      - "2181:2181"
    networks:
      - elkk

  kafka:
    build:
      context: .
      dockerfile: ./kafka/Dockerfile
    ports:
      - "9092:9092"
    volumes:
      - type: bind
        source: ./kafka/config/server.properties
        target: /opt/elkk/kafka/config/server.properties
    networks:
      - elkk
    depends_on:
      - zookeeper

networks:
  elkk:
    driver: bridge

volumes:
  elasticsearch:
    name: elasticsearch
